# Representing Data as Matrices

![](./images/Matrix.svg.png)

### Numpy and Matrices
The numpy package will provide you a great toolbox of optimized mathematical operations including the numpy array, the most convenient way to store vector and matrix data for computation. Here, we'll look at some basic operations in numpy.

In [1]:
import numpy as np

In [2]:
A = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4)) #Create a 3x4 matrix with random integers 0-9
B = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4)) #Create a 3x4 matrix with random integers 0-9

x = np.random.randn(4) #An array of 4 samples from the standard normal distribution
y = np.random.randn(5) #An array of 5 samples from the standard normal distribution

print('A: {}'.format(A))
print('\n')
print('B: {}'.format(B))

print('\n\n')
print('x: {}'.format(x))
print('\n\n')
print('y: {}'.format(y))

A: [[9 5 1 3]
 [8 7 8 7]
 [8 8 0 6]]


B: [[3 2 7 8]
 [8 0 9 3]
 [0 5 7 4]]



x: [-0.35576473 -1.01686544  1.52588145 -1.21832388]



y: [ 0.39919669  0.69873613 -0.49478598  1.13799641 -0.07052288]


In [3]:
print('A+B:\n', A+B, '\n\n') # matrix addition
print('A-B:\n', A-B, '\n\n') # matrix subtraction
print('Be careful! This is not standarad matrix multiplication!')
print('A*B:\n', A*B, '\n\n') # ELEMENTWISE multiplication
print('A/B:\n', A/B, '\n\n') # ELEMENTWISE division


print('A*x:\n', A*x, '\n\n') # multiply columns by x
print('A.T:\n', A.T, '\n\n') # transpose (just changes row/column ordering)
print('x.T:\n', x.T, '\n\n') # does nothing (can't transpose 1D array)

A+B:
 [[12  7  8 11]
 [16  7 17 10]
 [ 8 13  7 10]] 


A-B:
 [[ 6  3 -6 -5]
 [ 0  7 -1  4]
 [ 8  3 -7  2]] 


Be careful! This is not standarad matrix multiplication!
A*B:
 [[27 10  7 24]
 [64  0 72 21]
 [ 0 40  0 24]] 


A/B:
 [[3.         2.5        0.14285714 0.375     ]
 [1.                inf 0.88888889 2.33333333]
 [       inf 1.6        0.         1.5       ]] 


A*x:
 [[-3.20188254 -5.08432721  1.52588145 -3.65497165]
 [-2.84611781 -7.1180581  12.20705163 -8.52826718]
 [-2.84611781 -8.13492354  0.         -7.30994329]] 


A.T:
 [[9 8 8]
 [5 7 8]
 [1 8 0]
 [3 7 6]] 


x.T:
 [-0.35576473 -1.01686544  1.52588145 -1.21832388] 




/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


### 1. Generating Test Data
Generate two matrices of random data, A and B.  
Make matrix A a 3x4 matrix, and make B 4x4 matrix. Print both.

Calculate and print the following:
* $A^T$
* $B^T$
* AB
* $AB^T$
* $BA^T$

In [5]:
A = np.array([np.random.randint(0,10) for i in range(12)]).reshape((3,4)) #Your code goes here
B = np.array([np.random.randint(0,10) for i in range(16)]).reshape((4,4)) #Your code goes here
print('A :', A)
print('B :', B)

A : [[1 6 3 2]
 [1 1 7 8]
 [1 3 5 8]]
B : [[6 7 4 6]
 [4 4 3 0]
 [3 8 8 5]
 [9 0 4 0]]


In [7]:
transpose_of_b = B.transpose()#Your answer goes here
print('Transpose of B: {}'.format(transpose_of_b))

Transpose of B: [[6 4 3 9]
 [7 4 8 0]
 [4 3 8 4]
 [6 0 5 0]]


In [12]:
print('AB:',np.matmul(A,B)  ) #Your code goes here
print('AB^T:',np.matmul(A,B.transpose()) ) #Your code goes here
print('BA^T:',np.matmul(B,A.transpose())) #Your code goes here

AB: [[ 57  55  54  21]
 [103  67  95  41]
 [105  59  85  31]]
AB^T: [[ 72  37  85  21]
 [ 89  29 107  37]
 [ 95  31 107  29]]
BA^T: [[ 72  89  95]
 [ 37  29  31]
 [ 85 107 107]
 [ 21  37  29]]


#### 2. Describe what happens when you take the transpose of a matrix.

Describe the transpose of a matrix here.

### Systems of Equations
If you recall from your earlier life as a algebra student:

$2x +10 = 18$ has a unique solution; one variable, one equation, one solution

Similarly, two variables with two equations has one solution*   
$x+y=4$  
$2x+2y=10$

However, if we allow 2 variables with only 1 equation, we can have infinite solutions.
$x+y=4$

*(An inconsistent system will have no solution and a system where the second equation is a multiple of the first will have infinite solutions)

### 3. Representing Data as Matrices

#### A. Write a Matrix to represent this system:   
$x+y=4$  
$2x+2y=10$

In [13]:
#Your matrix goes here
A = A = np.array([[1,1,4],
     [2,2,10]
    ])

#### B. Multiply your matrix by 3. What is the resulting system of equations? 

In [15]:
A * 3 #Multiplying Matrix Here

array([[ 3,  3, 12],
       [ 6,  6, 30]])

## Write the resulting system here  
$3x+3y=12$  
$6x+6y=30$

### The Identity Matrix
The identity Matrix has ones running along the diagonal, and zeros everywhere else.
You can create an identity matrix of any given size by calling the built in numpy method:
numpy.identity(n) where n is the dimension of the desired matrix.

In [16]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 4. Multiply a matrix by the identity matrix. What do you notice? Explain why this happens.

In [19]:
np.matmul(A,np.identity(3))#Multiply a matrix by the identity matrix here.

array([[ 1.,  1.,  4.],
       [ 2.,  2., 10.]])

#Write your observations and explanation here.